version: '3.9'

services:
  nginx:
    build:
      context: .
      target: nginx_base
    volumes:
      - ./:/srv/app:ro,cached
      - php_socket:/var/run/php
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app

  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    environment:
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    depends_on:
      - db
    networks:
      - app

  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    ports:
      - "3306:3306"
    networks:
      - app

volumes:
  php_socket:
  db_app:

networks:
  app:
    driver: bridge
